# Generated by Django 4.2.3 on 2023-09-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Titulo')),
                ('descriptions', models.TextField(verbose_name='Descripcion')),
                ('due_data', models.DateField()),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Tarea',
                'ordering': ['status'],
            },
        ),
    ]
